name: Axe (Playwright) smoke

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      fail_on_violations:
        description: 'Fail workflow when any axe violations are found'
        required: false
        default: 'false'

jobs:
  run-axe:
    name: Run axe across examples with Playwright
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      # default to 'false' when not provided; workflow_dispatch may set this input
      FAIL_ON_VIOLATIONS: ${{ github.event.inputs.fail_on_violations || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start static server
        run: |
          nohup npx http-server ./ -p 8080 -c-1 > server.log 2>&1 &
          # wait until server responds on 8080 (max ~15s)
          for i in {1..15}; do
            if curl -sSf http://127.0.0.1:8080 >/dev/null; then
              echo 'server up'; break
            fi; sleep 1;
          done

      - name: Run axe helper (Playwright)
        run: |
          echo "Running axe helper (fail on violations = ${FAIL_ON_VIOLATIONS})"
          node scripts/ci-run-axe.js --base-url=http://127.0.0.1:8080 --out-dir=axe-output --fail-on-violations=${FAIL_ON_VIOLATIONS}

      - name: Show results
        run: |
          echo 'axe-output contents:'
          ls -la axe-output || true

      - name: Upload axe JSON artifacts
        uses: actions/upload-artifact@v4
        with:
          name: axe-output
          path: axe-output/
