name: HTML Validate (PR)

on:
  pull_request:
    paths:
      - '**/*.html'
      - 'jim-viewer.html'
      - 'examples/**'
      - '.github/workflows/**'

jobs:
  html-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run html-validate (via npx)
        run: |
          echo "Running html-validate via npx..."
          npx --yes html-validate --version
          # Validate the viewer and HTML files in examples
          npx --yes html-validate "jim-viewer.html" "**/*.html" || (echo "html-validate reported errors" && exit 1)
