name: HTML Validate (PR)

on:
  pull_request:
    paths:
      - '**/*.html'
      - 'jim-viewer.html'
      - 'examples/**'
      - '.github/workflows/**'

jobs:
  html-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run html-validate (via npx)
        run: |
          echo "Running html-validate via npx..."
          npx --yes html-validate --version
          # Validate the viewer and HTML files in examples
          npx --yes html-validate "jim-viewer.html" "**/*.html" || (echo "html-validate reported errors" && exit 1)

  a11y-smoke:
    name: Accessibility smoke (pa11y)
    runs-on: ubuntu-latest
    needs: html-validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install http-server globally
        run: |
          npm install -g http-server

      - name: Start simple static server
        run: |
          # serve the repository root so jim-viewer.html is reachable
          npx http-server -p 8080 &
          # give server a moment to start
          sleep 2

      - name: Run pa11y accessibility scan
        # pa11y will use a headless Chromium under the hood; run against the local server
        run: |
          npx --yes pa11y http://127.0.0.1:8080/jim-viewer.html || (echo "pa11y reported accessibility issues" && exit 1)
